insert into block_party_datetime (date, time_of_day) values ('2015-09-04', "Morning");
insert into block_party_datetime (date, time_of_day) values ('2015-09-04', "Afternoon");
insert into block_party_datetime (date, time_of_day) values ('2015-09-04', "Evening");
insert into block_party_datetime (date, time_of_day) values ('2015-09-05', "Morning");
insert into block_party_datetime (date, time_of_day) values ('2015-09-05', "Afternoon");
insert into block_party_datetime (date, time_of_day) values ('2015-09-05', "Evening");
insert into block_party_datetime (date, time_of_day) values ('2015-09-06', "Morning");
insert into block_party_datetime (date, time_of_day) values ('2015-09-06', "Afternoon");
insert into block_party_datetime (date, time_of_day) values ('2015-09-06', "Evening");