insert into block_party_datetime (id, date, time_of_day) values (1, '2015-09-04', "Morning");
insert into block_party_datetime (id, date, time_of_day) values (2, '2015-09-04', "Afternoon");
insert into block_party_datetime (id, date, time_of_day) values (3, '2015-09-04', "Evening");
insert into block_party_datetime (id, date, time_of_day) values (4, '2015-09-05', "Morning");
insert into block_party_datetime (id, date, time_of_day) values (5, '2015-09-05', "Afternoon");
insert into block_party_datetime (id, date, time_of_day) values (6, '2015-09-05', "Evening");
insert into block_party_datetime (id, date, time_of_day) values (7, '2015-09-06', "Morning");
insert into block_party_datetime (id, date, time_of_day) values (8, '2015-09-06', "Afternoon");
insert into block_party_datetime (id, date, time_of_day) values (9, '2015-09-06', "Evening");